name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: gengjiawen/gitbook
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build books
        env:
          QTWEBENGINE_DISABLE_SANDBOX: 1
        run: |
          mkdir dist
          gitbook epub ./ dist/koa-design.epub
          gitbook epub ./ dist/koa-design.epub
          ebook-convert dist/koa-design.epub dist/koa-design.pdf
          # gitbook pdf ./ dist/koa-design.pdf
          ls -lh -R dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
